/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'quickstart',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      collapsible: true,
      collapsed: true,
      items: [
        'linking',
        'notification',
        'richmenu',
      ],
    },
    'settings',
    'eventlog',
    'bulkmessage',
    'dm',
    'trigger',
    'message',
    'audience',
    'scenario',
    'actionflow',
    'action-execute',
    {
      type: 'category',
      label: 'For developers',
      collapsible: true,
      collapsed: true,
      items: [
        'hook',
        'filter',
        'store'
      ],
    },
    'wplogin',
  ],
};

export default sidebars;
