/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'quickstart',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      collapsible: true,
      collapsed: true,
      items: [
        'linking',
        'notification',
        'richmenu',
      ],
    },
    'dashboard',
    'bulkmessage',
    'action-execute',
    'chat',
    'audience',
    'message',
    'scenario',
    'actionflow',
    'trigger',
    'interaction',
    'eventlog',
    'settings',
    {
      type: 'category',
      label: 'For developers',
      collapsible: true,
      collapsed: true,
      items: [
        'hook',
        {
          type: 'category',
          label: 'Filter hooks',
          link: {
            type: 'doc',
            id: 'filter/index',
          },
          items: [
            'filter/actions/index',
            'filter/post-notification/index',
            'filter/message-sending/index',
            'filter/wp-user-alternative/index',
            'filter/schema-related/index',
            'filter/settings-related/index',
            'filter/translation-related/index',
            'filter/trigger-related/index',
            'filter/interaction-related/index',
            'filter/http-client-related/index',
          ],
        },
        'store'
      ],
    },
    'aichatbot',
    'wplogin',
    'faq',
  ],
};

export default sidebars;
